# Generated by Django 3.2.4 on 2021-06-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SpaceShips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ship_class', models.CharField(max_length=200, verbose_name='Class')),
                ('description', models.TextField()),
                ('ship_types', models.CharField(choices=[('FR', 'Frigate'), ('RA', 'Racing ship')], default='FR', max_length=2, verbose_name='Type')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_ships', to='expanse.pilot')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
