# Generated by Django 3.2.4 on 2021-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse', '0002_pilot_human'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceships',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
